; Auto-generated. Do not edit!


(cl:in-package cares_msgs-msg)


;//! \htmlinclude MetricExtractionResult.msg.html

(cl:defclass <MetricExtractionResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:fixnum
    :initform 0))
)

(cl:defclass MetricExtractionResult (<MetricExtractionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MetricExtractionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MetricExtractionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cares_msgs-msg:<MetricExtractionResult> is deprecated: use cares_msgs-msg:MetricExtractionResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <MetricExtractionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cares_msgs-msg:result-val is deprecated.  Use cares_msgs-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MetricExtractionResult>) ostream)
  "Serializes a message object of type '<MetricExtractionResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'result)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MetricExtractionResult>) istream)
  "Deserializes a message object of type '<MetricExtractionResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'result)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MetricExtractionResult>)))
  "Returns string type for a message object of type '<MetricExtractionResult>"
  "cares_msgs/MetricExtractionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MetricExtractionResult)))
  "Returns string type for a message object of type 'MetricExtractionResult"
  "cares_msgs/MetricExtractionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MetricExtractionResult>)))
  "Returns md5sum for a message object of type '<MetricExtractionResult>"
  "25458147911545c320c4c0a299eff763")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MetricExtractionResult)))
  "Returns md5sum for a message object of type 'MetricExtractionResult"
  "25458147911545c320c4c0a299eff763")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MetricExtractionResult>)))
  "Returns full string definition for message of type '<MetricExtractionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%uint8 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MetricExtractionResult)))
  "Returns full string definition for message of type 'MetricExtractionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%uint8 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MetricExtractionResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MetricExtractionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MetricExtractionResult
    (cl:cons ':result (result msg))
))
