// Generated by gencpp from file cares_msgs/MappingGoal.msg
// DO NOT EDIT!


#ifndef CARES_MSGS_MESSAGE_MAPPINGGOAL_H
#define CARES_MSGS_MESSAGE_MAPPINGGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <cares_msgs/ScanningGoal.h>
#include <cares_msgs/MetricExtractionGoal.h>

namespace cares_msgs
{
template <class ContainerAllocator>
struct MappingGoal_
{
  typedef MappingGoal_<ContainerAllocator> Type;

  MappingGoal_()
    : command(0)
    , scanning_goals()
    , metric_goal()  {
    }
  MappingGoal_(const ContainerAllocator& _alloc)
    : command(0)
    , scanning_goals(_alloc)
    , metric_goal(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _command_type;
  _command_type command;

   typedef std::vector< ::cares_msgs::ScanningGoal_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cares_msgs::ScanningGoal_<ContainerAllocator> >::other >  _scanning_goals_type;
  _scanning_goals_type scanning_goals;

   typedef  ::cares_msgs::MetricExtractionGoal_<ContainerAllocator>  _metric_goal_type;
  _metric_goal_type metric_goal;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(STOP)
  #undef STOP
#endif
#if defined(_WIN32) && defined(MAP)
  #undef MAP
#endif
#if defined(_WIN32) && defined(ACTUATE)
  #undef ACTUATE
#endif

  enum {
    STOP = 0u,
    MAP = 1u,
    ACTUATE = 3u,
  };


  typedef boost::shared_ptr< ::cares_msgs::MappingGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cares_msgs::MappingGoal_<ContainerAllocator> const> ConstPtr;

}; // struct MappingGoal_

typedef ::cares_msgs::MappingGoal_<std::allocator<void> > MappingGoal;

typedef boost::shared_ptr< ::cares_msgs::MappingGoal > MappingGoalPtr;
typedef boost::shared_ptr< ::cares_msgs::MappingGoal const> MappingGoalConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cares_msgs::MappingGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cares_msgs::MappingGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cares_msgs::MappingGoal_<ContainerAllocator1> & lhs, const ::cares_msgs::MappingGoal_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command &&
    lhs.scanning_goals == rhs.scanning_goals &&
    lhs.metric_goal == rhs.metric_goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cares_msgs::MappingGoal_<ContainerAllocator1> & lhs, const ::cares_msgs::MappingGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cares_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cares_msgs::MappingGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cares_msgs::MappingGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cares_msgs::MappingGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cares_msgs::MappingGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cares_msgs::MappingGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cares_msgs::MappingGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cares_msgs::MappingGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f45265005af9eb076d6afb20e6b32c3b";
  }

  static const char* value(const ::cares_msgs::MappingGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf45265005af9eb07ULL;
  static const uint64_t static_value2 = 0x6d6afb20e6b32c3bULL;
};

template<class ContainerAllocator>
struct DataType< ::cares_msgs::MappingGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cares_msgs/MappingGoal";
  }

  static const char* value(const ::cares_msgs::MappingGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cares_msgs::MappingGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"# Mapping Command Enumeration\n"
"uint8 STOP    = 0\n"
"uint8 MAP     = 1\n"
"uint8 ACTUATE = 3 # e.g. prune/pick/thin\n"
"\n"
"uint8 command\n"
"\n"
"cares_msgs/ScanningGoal[] scanning_goals\n"
"cares_msgs/MetricExtractionGoal metric_goal\n"
"\n"
"================================================================================\n"
"MSG: cares_msgs/ScanningGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"# Arm Command Enumeration\n"
"uint8 STOP    = 0\n"
"uint8 MAP     = 1\n"
"uint8 MOVE    = 2 # Move Arm to Position\n"
"uint8 ACTUATE = 3 # e.g. prune/pick/thin\n"
"\n"
"# Arm command\n"
"uint8 command\n"
"\n"
"# Initial Pose to move arm too\n"
"geometry_msgs/PoseStamped init_pose\n"
"\n"
"# Planning Link\n"
"std_msgs/String planning_link\n"
"\n"
"# World Link\n"
"std_msgs/String world_link\n"
"\n"
"# To seek out alignment marker or not before scanning\n"
"std_msgs/Bool get_marker\n"
"\n"
"# Path ID from path factory to generate scanning path\n"
"uint8 path_id\n"
"\n"
"# Path to save data too\n"
"std_msgs/String file_path\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
"================================================================================\n"
"MSG: cares_msgs/MetricExtractionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"# Arm Command Enumeration\n"
"uint8 RESET    = 0\n"
"uint8 CAPTURE  = 1\n"
"uint8 MEASURE  = 2\n"
"\n"
"# Arm command\n"
"uint8 command\n"
"\n"
"# Path to save data too\n"
"std_msgs/String file_path\n"
;
  }

  static const char* value(const ::cares_msgs::MappingGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cares_msgs::MappingGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.scanning_goals);
      stream.next(m.metric_goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MappingGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cares_msgs::MappingGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cares_msgs::MappingGoal_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
    s << indent << "scanning_goals[]" << std::endl;
    for (size_t i = 0; i < v.scanning_goals.size(); ++i)
    {
      s << indent << "  scanning_goals[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cares_msgs::ScanningGoal_<ContainerAllocator> >::stream(s, indent + "    ", v.scanning_goals[i]);
    }
    s << indent << "metric_goal: ";
    s << std::endl;
    Printer< ::cares_msgs::MetricExtractionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.metric_goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARES_MSGS_MESSAGE_MAPPINGGOAL_H
