// Generated by gencpp from file cares_msgs/MetricExtractionResult.msg
// DO NOT EDIT!


#ifndef CARES_MSGS_MESSAGE_METRICEXTRACTIONRESULT_H
#define CARES_MSGS_MESSAGE_METRICEXTRACTIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cares_msgs
{
template <class ContainerAllocator>
struct MetricExtractionResult_
{
  typedef MetricExtractionResult_<ContainerAllocator> Type;

  MetricExtractionResult_()
    : result(0)  {
    }
  MetricExtractionResult_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::cares_msgs::MetricExtractionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cares_msgs::MetricExtractionResult_<ContainerAllocator> const> ConstPtr;

}; // struct MetricExtractionResult_

typedef ::cares_msgs::MetricExtractionResult_<std::allocator<void> > MetricExtractionResult;

typedef boost::shared_ptr< ::cares_msgs::MetricExtractionResult > MetricExtractionResultPtr;
typedef boost::shared_ptr< ::cares_msgs::MetricExtractionResult const> MetricExtractionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cares_msgs::MetricExtractionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cares_msgs::MetricExtractionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cares_msgs::MetricExtractionResult_<ContainerAllocator1> & lhs, const ::cares_msgs::MetricExtractionResult_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cares_msgs::MetricExtractionResult_<ContainerAllocator1> & lhs, const ::cares_msgs::MetricExtractionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cares_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cares_msgs::MetricExtractionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cares_msgs::MetricExtractionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cares_msgs::MetricExtractionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cares_msgs::MetricExtractionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cares_msgs::MetricExtractionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cares_msgs::MetricExtractionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cares_msgs::MetricExtractionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25458147911545c320c4c0a299eff763";
  }

  static const char* value(const ::cares_msgs::MetricExtractionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25458147911545c3ULL;
  static const uint64_t static_value2 = 0x20c4c0a299eff763ULL;
};

template<class ContainerAllocator>
struct DataType< ::cares_msgs::MetricExtractionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cares_msgs/MetricExtractionResult";
  }

  static const char* value(const ::cares_msgs::MetricExtractionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cares_msgs::MetricExtractionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"uint8 result\n"
;
  }

  static const char* value(const ::cares_msgs::MetricExtractionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cares_msgs::MetricExtractionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MetricExtractionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cares_msgs::MetricExtractionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cares_msgs::MetricExtractionResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARES_MSGS_MESSAGE_METRICEXTRACTIONRESULT_H
