// Generated by gencpp from file cares_msgs/ScanningFeedback.msg
// DO NOT EDIT!


#ifndef CARES_MSGS_MESSAGE_SCANNINGFEEDBACK_H
#define CARES_MSGS_MESSAGE_SCANNINGFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cares_msgs
{
template <class ContainerAllocator>
struct ScanningFeedback_
{
  typedef ScanningFeedback_<ContainerAllocator> Type;

  ScanningFeedback_()
    : status(0)
    , arm_status(0)
    , count(0)
    , total(0)  {
    }
  ScanningFeedback_(const ContainerAllocator& _alloc)
    : status(0)
    , arm_status(0)
    , count(0)
    , total(0)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;

   typedef uint8_t _arm_status_type;
  _arm_status_type arm_status;

   typedef uint8_t _count_type;
  _count_type count;

   typedef uint8_t _total_type;
  _total_type total;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(INIT)
  #undef INIT
#endif
#if defined(_WIN32) && defined(MARKER)
  #undef MARKER
#endif
#if defined(_WIN32) && defined(CAPTURING)
  #undef CAPTURING
#endif
#if defined(_WIN32) && defined(ERROR)
  #undef ERROR
#endif
#if defined(_WIN32) && defined(MOVING)
  #undef MOVING
#endif
#if defined(_WIN32) && defined(IDLE)
  #undef IDLE
#endif

  enum {
    INIT = 0u,
    MARKER = 1u,
    CAPTURING = 2u,
    ERROR = 3u,
    MOVING = 4u,
    IDLE = 5u,
  };


  typedef boost::shared_ptr< ::cares_msgs::ScanningFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cares_msgs::ScanningFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ScanningFeedback_

typedef ::cares_msgs::ScanningFeedback_<std::allocator<void> > ScanningFeedback;

typedef boost::shared_ptr< ::cares_msgs::ScanningFeedback > ScanningFeedbackPtr;
typedef boost::shared_ptr< ::cares_msgs::ScanningFeedback const> ScanningFeedbackConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cares_msgs::ScanningFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cares_msgs::ScanningFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cares_msgs::ScanningFeedback_<ContainerAllocator1> & lhs, const ::cares_msgs::ScanningFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.arm_status == rhs.arm_status &&
    lhs.count == rhs.count &&
    lhs.total == rhs.total;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cares_msgs::ScanningFeedback_<ContainerAllocator1> & lhs, const ::cares_msgs::ScanningFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cares_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cares_msgs::ScanningFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cares_msgs::ScanningFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cares_msgs::ScanningFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cares_msgs::ScanningFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cares_msgs::ScanningFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cares_msgs::ScanningFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cares_msgs::ScanningFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d3d7a2c3531d2f3341f1246606350603";
  }

  static const char* value(const ::cares_msgs::ScanningFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd3d7a2c3531d2f33ULL;
  static const uint64_t static_value2 = 0x41f1246606350603ULL;
};

template<class ContainerAllocator>
struct DataType< ::cares_msgs::ScanningFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cares_msgs/ScanningFeedback";
  }

  static const char* value(const ::cares_msgs::ScanningFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cares_msgs::ScanningFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"\n"
"#Enumeration\n"
"uint8 INIT       = 0\n"
"uint8 MARKER     = 1\n"
"uint8 CAPTURING  = 2\n"
"uint8 ERROR      = 3\n"
"#Task status\n"
"uint8 status\n"
"\n"
"#Enumeration\n"
"uint8 MOVING  = 4\n"
"uint8 IDLE    = 5\n"
"uint8 arm_status\n"
"\n"
"uint8 count\n"
"uint8 total\n"
;
  }

  static const char* value(const ::cares_msgs::ScanningFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cares_msgs::ScanningFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.arm_status);
      stream.next(m.count);
      stream.next(m.total);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ScanningFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cares_msgs::ScanningFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cares_msgs::ScanningFeedback_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "arm_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.arm_status);
    s << indent << "count: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.count);
    s << indent << "total: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.total);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARES_MSGS_MESSAGE_SCANNINGFEEDBACK_H
