// Generated by gencpp from file cares_msgs/ScanningGoal.msg
// DO NOT EDIT!


#ifndef CARES_MSGS_MESSAGE_SCANNINGGOAL_H
#define CARES_MSGS_MESSAGE_SCANNINGGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>
#include <std_msgs/String.h>
#include <std_msgs/String.h>
#include <std_msgs/Bool.h>
#include <std_msgs/String.h>

namespace cares_msgs
{
template <class ContainerAllocator>
struct ScanningGoal_
{
  typedef ScanningGoal_<ContainerAllocator> Type;

  ScanningGoal_()
    : command(0)
    , init_pose()
    , planning_link()
    , world_link()
    , get_marker()
    , path_id(0)
    , file_path()  {
    }
  ScanningGoal_(const ContainerAllocator& _alloc)
    : command(0)
    , init_pose(_alloc)
    , planning_link(_alloc)
    , world_link(_alloc)
    , get_marker(_alloc)
    , path_id(0)
    , file_path(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _command_type;
  _command_type command;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _init_pose_type;
  _init_pose_type init_pose;

   typedef  ::std_msgs::String_<ContainerAllocator>  _planning_link_type;
  _planning_link_type planning_link;

   typedef  ::std_msgs::String_<ContainerAllocator>  _world_link_type;
  _world_link_type world_link;

   typedef  ::std_msgs::Bool_<ContainerAllocator>  _get_marker_type;
  _get_marker_type get_marker;

   typedef uint8_t _path_id_type;
  _path_id_type path_id;

   typedef  ::std_msgs::String_<ContainerAllocator>  _file_path_type;
  _file_path_type file_path;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(STOP)
  #undef STOP
#endif
#if defined(_WIN32) && defined(MAP)
  #undef MAP
#endif
#if defined(_WIN32) && defined(MOVE)
  #undef MOVE
#endif
#if defined(_WIN32) && defined(ACTUATE)
  #undef ACTUATE
#endif

  enum {
    STOP = 0u,
    MAP = 1u,
    MOVE = 2u,
    ACTUATE = 3u,
  };


  typedef boost::shared_ptr< ::cares_msgs::ScanningGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cares_msgs::ScanningGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ScanningGoal_

typedef ::cares_msgs::ScanningGoal_<std::allocator<void> > ScanningGoal;

typedef boost::shared_ptr< ::cares_msgs::ScanningGoal > ScanningGoalPtr;
typedef boost::shared_ptr< ::cares_msgs::ScanningGoal const> ScanningGoalConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cares_msgs::ScanningGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cares_msgs::ScanningGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cares_msgs::ScanningGoal_<ContainerAllocator1> & lhs, const ::cares_msgs::ScanningGoal_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command &&
    lhs.init_pose == rhs.init_pose &&
    lhs.planning_link == rhs.planning_link &&
    lhs.world_link == rhs.world_link &&
    lhs.get_marker == rhs.get_marker &&
    lhs.path_id == rhs.path_id &&
    lhs.file_path == rhs.file_path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cares_msgs::ScanningGoal_<ContainerAllocator1> & lhs, const ::cares_msgs::ScanningGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cares_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cares_msgs::ScanningGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cares_msgs::ScanningGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cares_msgs::ScanningGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cares_msgs::ScanningGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cares_msgs::ScanningGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cares_msgs::ScanningGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cares_msgs::ScanningGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cae2bb73f288441970bca461bed96dca";
  }

  static const char* value(const ::cares_msgs::ScanningGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcae2bb73f2884419ULL;
  static const uint64_t static_value2 = 0x70bca461bed96dcaULL;
};

template<class ContainerAllocator>
struct DataType< ::cares_msgs::ScanningGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cares_msgs/ScanningGoal";
  }

  static const char* value(const ::cares_msgs::ScanningGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cares_msgs::ScanningGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"# Arm Command Enumeration\n"
"uint8 STOP    = 0\n"
"uint8 MAP     = 1\n"
"uint8 MOVE    = 2 # Move Arm to Position\n"
"uint8 ACTUATE = 3 # e.g. prune/pick/thin\n"
"\n"
"# Arm command\n"
"uint8 command\n"
"\n"
"# Initial Pose to move arm too\n"
"geometry_msgs/PoseStamped init_pose\n"
"\n"
"# Planning Link\n"
"std_msgs/String planning_link\n"
"\n"
"# World Link\n"
"std_msgs/String world_link\n"
"\n"
"# To seek out alignment marker or not before scanning\n"
"std_msgs/Bool get_marker\n"
"\n"
"# Path ID from path factory to generate scanning path\n"
"uint8 path_id\n"
"\n"
"# Path to save data too\n"
"std_msgs/String file_path\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
;
  }

  static const char* value(const ::cares_msgs::ScanningGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cares_msgs::ScanningGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.init_pose);
      stream.next(m.planning_link);
      stream.next(m.world_link);
      stream.next(m.get_marker);
      stream.next(m.path_id);
      stream.next(m.file_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ScanningGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cares_msgs::ScanningGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cares_msgs::ScanningGoal_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
    s << indent << "init_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.init_pose);
    s << indent << "planning_link: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.planning_link);
    s << indent << "world_link: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.world_link);
    s << indent << "get_marker: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.get_marker);
    s << indent << "path_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.path_id);
    s << indent << "file_path: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.file_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARES_MSGS_MESSAGE_SCANNINGGOAL_H
