// Generated by gencpp from file rigid2d/SetPose.msg
// DO NOT EDIT!


#ifndef RIGID2D_MESSAGE_SETPOSE_H
#define RIGID2D_MESSAGE_SETPOSE_H

#include <ros/service_traits.h>


#include <rigid2d/SetPoseRequest.h>
#include <rigid2d/SetPoseResponse.h>


namespace rigid2d
{

struct SetPose
{

typedef SetPoseRequest Request;
typedef SetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPose
} // namespace rigid2d


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rigid2d::SetPose > {
  static const char* value()
  {
    return "938fa65709584ad8e77d238529be13b8";
  }

  static const char* value(const ::rigid2d::SetPose&) { return value(); }
};

template<>
struct DataType< ::rigid2d::SetPose > {
  static const char* value()
  {
    return "rigid2d/SetPose";
  }

  static const char* value(const ::rigid2d::SetPose&) { return value(); }
};


// service_traits::MD5Sum< ::rigid2d::SetPoseRequest> should match
// service_traits::MD5Sum< ::rigid2d::SetPose >
template<>
struct MD5Sum< ::rigid2d::SetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rigid2d::SetPose >::value();
  }
  static const char* value(const ::rigid2d::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rigid2d::SetPoseRequest> should match
// service_traits::DataType< ::rigid2d::SetPose >
template<>
struct DataType< ::rigid2d::SetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::rigid2d::SetPose >::value();
  }
  static const char* value(const ::rigid2d::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rigid2d::SetPoseResponse> should match
// service_traits::MD5Sum< ::rigid2d::SetPose >
template<>
struct MD5Sum< ::rigid2d::SetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rigid2d::SetPose >::value();
  }
  static const char* value(const ::rigid2d::SetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rigid2d::SetPoseResponse> should match
// service_traits::DataType< ::rigid2d::SetPose >
template<>
struct DataType< ::rigid2d::SetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::rigid2d::SetPose >::value();
  }
  static const char* value(const ::rigid2d::SetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RIGID2D_MESSAGE_SETPOSE_H
