// Generated by gencpp from file rigid2d/SetPoseRequest.msg
// DO NOT EDIT!


#ifndef RIGID2D_MESSAGE_SETPOSEREQUEST_H
#define RIGID2D_MESSAGE_SETPOSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rigid2d
{
template <class ContainerAllocator>
struct SetPoseRequest_
{
  typedef SetPoseRequest_<ContainerAllocator> Type;

  SetPoseRequest_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
    }
  SetPoseRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::rigid2d::SetPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rigid2d::SetPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetPoseRequest_

typedef ::rigid2d::SetPoseRequest_<std::allocator<void> > SetPoseRequest;

typedef boost::shared_ptr< ::rigid2d::SetPoseRequest > SetPoseRequestPtr;
typedef boost::shared_ptr< ::rigid2d::SetPoseRequest const> SetPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rigid2d::SetPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rigid2d::SetPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rigid2d::SetPoseRequest_<ContainerAllocator1> & lhs, const ::rigid2d::SetPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rigid2d::SetPoseRequest_<ContainerAllocator1> & lhs, const ::rigid2d::SetPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rigid2d

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rigid2d::SetPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rigid2d::SetPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rigid2d::SetPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rigid2d::SetPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rigid2d::SetPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rigid2d::SetPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rigid2d::SetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "938fa65709584ad8e77d238529be13b8";
  }

  static const char* value(const ::rigid2d::SetPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x938fa65709584ad8ULL;
  static const uint64_t static_value2 = 0xe77d238529be13b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::rigid2d::SetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rigid2d/SetPoseRequest";
  }

  static const char* value(const ::rigid2d::SetPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rigid2d::SetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::rigid2d::SetPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rigid2d::SetPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rigid2d::SetPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rigid2d::SetPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIGID2D_MESSAGE_SETPOSEREQUEST_H
